### ISSUE TITLE
ownership for cumulus driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation-community/napalm-cumulus#21]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested; @jmrenshaw @GGabriele 

If you have questions/comments let me know.

Regards

**Comment by jmrenshaw** [comment]
Hi @dbarrosop ,
Happy to help out, what would it entail?

**Comment by dbarrosop** [comment]
Basically maintaining the repo. Someone has to check issues, review/merge PRs, release new versions, etc... Regular lifecycle of a software project :) As it is right now the project deserted so it'd be great if someone would take it.

**Comment by jmrenshaw** [comment]
Hi @dbarrosop happy to take this one on as a side project seeing as there's not much other activity going on here.  I've noticed since the repo has been moved to community that the build status is showing as unknown.  What do I need to do to get that rectified?

**Comment by dbarrosop** [comment]
Just gave you admin access to this repo. Let me know if you need anything else.
