### ISSUE TITLE
get_config

### ISSUE THREAD

**Issue by jmrenshaw** [napalm-automation-community/napalm-cumulus#22]
Implement the get_config method.

**Comment by jmrenshaw** [comment]
I have written up most of this one but it is currently failing pytest.   

> "Failed: No test case for 'test_get_config_filtered' found"

@dbarrosop could you point me in the direction of the documentation explaining what this test does?

**Comment by dbarrosop** [comment]
The test is here, it's basically testing you can get only the "running" or the "startup" config if needed:

https://github.com/napalm-automation/napalm/blob/890b93690ca68bd7e816bd6ac3098e63da1abee6/napalm/base/test/getters.py#L496

It's actually a strange test and looking at it now I am doubting it does anything useful :S
