### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by Otterian** [napalm-automation-community/napalm-cumulus#48]
Greetings,

Is this project abandoned by the maintainer? The package(s) are missing from PyPi and there has been no new commits in months.
Or has Cumulus Linux been adopted into the mainstream NAPALM project?

**Comment by Phill93** [comment]
Hello, I need this driver. What is the status of the project?

**Comment by jmrenshaw** [comment]
Hi both, there hasn't been much activity here.  There is still development required to get it to a reasonable amount of coverage of the functions Napalm provides.  It is currently a community driver outside of the main Napalm project.  If there are any particular functions you require please create issues for them and maybe someone will pick them up and add it to the project.

**Comment by bowersjj** [comment]
I'm plugging away at this. I use Cumulus so I'm invested in getting this driver functional.
My expectation is to have the driver fully functional by the middle of next year at the latest, hopefully a lot sooner.
I'm reviewing the existing code and fixing issues as I come across them.
Create an issue if there is a function you are looking for, or if anything in the current code is broken.
